2025-03-02 15:26:10,879 INFO    MainThread:4584 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_setup.py:_flush():67] Configure stats pid to 4584
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_setup.py:_flush():67] Loading settings from C:\Users\13580\.config\wandb\settings
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_setup.py:_flush():67] Loading settings from C:\Users\13580\PycharmProjects\DRL_ORAN_Power\wandb\settings
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\13580\PycharmProjects\DRL_ORAN_Power\wandb\run-20250302_152610-5q32ap08\logs\debug.log
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\13580\PycharmProjects\DRL_ORAN_Power\wandb\run-20250302_152610-5q32ap08\logs\debug-internal.log
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_init.py:init():761] calling init triggers
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'max_step': 50, 'num_episodes': 500, 'last_n': 10, 'actor_lr': 0.0003, 'critic_lr': 0.001, 'dqn_lr': 0.001, 'gamma': 0.99, 'epsilon': 1.0, 'epsilon_min': 0.01, 'epsilon_decay': 0.99, 'state_space': 50, 'action_space': 128, 'seed': 42, 'env': 'sim', 'agent': 'dqn', '_wandb': {}}
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_init.py:init():784] starting backend
2025-03-02 15:26:10,880 INFO    MainThread:4584 [wandb_init.py:init():788] sending inform_init request
2025-03-02 15:26:10,901 INFO    MainThread:4584 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-02 15:26:10,902 INFO    MainThread:4584 [wandb_init.py:init():803] backend started and connected
2025-03-02 15:26:10,903 INFO    MainThread:4584 [wandb_init.py:init():896] updated telemetry
2025-03-02 15:26:11,075 INFO    MainThread:4584 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 15:26:13,474 INFO    MainThread:4584 [wandb_init.py:init():995] starting run threads in backend
2025-03-02 15:26:13,971 INFO    MainThread:4584 [wandb_run.py:_console_start():2377] atexit reg
2025-03-02 15:26:13,971 INFO    MainThread:4584 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-02 15:26:13,971 INFO    MainThread:4584 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-02 15:26:13,971 INFO    MainThread:4584 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-02 15:26:13,974 INFO    MainThread:4584 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-02 15:26:14,058 WARNING MsgRouterThr:4584 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\13580\PycharmProjects\DRL_ORAN_Power\venv\lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "C:\Users\13580\PycharmProjects\DRL_ORAN_Power\venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\13580\PycharmProjects\DRL_ORAN_Power\venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\13580\PycharmProjects\DRL_ORAN_Power\venv\lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "C:\Users\13580\PycharmProjects\DRL_ORAN_Power\venv\lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 15:26:14,084 INFO    MsgRouterThr:4584 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
